# prettier-ignore
version: '3.5'

services:
    app:
        build: ./app
        volumes: 
            - ./app:/app
        working_dir: /app
        ports:
            - 3000:3000
        tty: true
